backchannel:

  # Settings regarding the poller, polling validation messages.
  broadcastValidationMessageInboundPoller:
    fixedDelay:                                                             10000
    initialDelay:                                                           10000
    maxFetchSize:                                                           1
    threadName:                                                             pol-brod-error-we-are-coming----- 
    threadCorePoolSize:                                                     1
    threadMaxPoolSize:                                                      1
  createFeedbackReport:
    threadName:                                                             report-creation-job-russel-peters
   # Capacity of the queue buffering report job creation requests.
    queuesize:                                                              1   
test: 
  go:                                                                       nice 
